spring.datasource.url=jdbc:mysql://localhost:3306/test

openapi.service-key=/99p4bK0LcTzFgaq97mbNe/oAWZex+7WDLf35/XJrIQElNWq+WR+Vghbe8FxySwatEcu4EVAFq8Tb8Yz/UK6Pw==

spring.datasource.username=root
spring.datasource.password=12345

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mybatis.mapper-locations=classpath:mapper/**/*.xml